deployment/factorycube-server/values.yaml
=> 220 Grafana is not starting

sensorconnect/src/iodd_files/ifm-0001A7-20160303-IODD1.1.xml, sensorconnect/src/iodd_files/ifm-000442-20181113-IODD1.1.xml, sensorconnect/src/main.py
=> Added additional sensors

deployment/factorycube-edge/Chart.yaml, deployment/factorycube-edge/templates/barcodereader-Deployment.yaml, deployment/factorycube-edge/templates/mqttbridge-Deployment.yaml, deployment/factorycube-edge/templates/nodered-StatefulSet.yaml, deployment/factorycube-edge/templates/sensorconnect-Deployment.yaml, deployment/factorycube-edge/values.yaml, deployment/factorycube-server/Chart.yaml, deployment/factorycube-server/values.yaml
=> 269 only pull docker images if not existing

docs/content/en/docs/Getting started/setup-development/index.md, docs/content/en/docs/Getting started/usage-in-production/index.md
=> Fixes #271

docs/content/en/docs/Getting started/setup-development/index.md, docs/content/en/docs/Tutorials/add-username-password-authentification-k3os-ssh/index.md
=> Fixed #207

docs/content/en/docs/Tutorials/pki/index.md
=> Fixed #266

docs/content/en/docs/_index.md
=> Fixed #284

deployment/factorycube-server/values.yaml
=> Fixed #267

docs/content/en/docs/Getting started/setup-development/index.md, docs/content/en/docs/Tutorials/how-to-fix-ntp-issues/index.md
=> Fixed #281

README.md, docs/content/en/docs/_index.md
=> Updated README

docs/content/en/docs/Developers/factorycube-server/factoryinsight/index.md
=> Standardized documentation for factoryinsight

docs/content/en/docs/Tutorials/how-to-fix-ntp-issues/index.md
=> Fix documentation for k3os cert expired

docs/content/en/docs/Tutorials/documentation/index.md
=> Fixes #332

cameraconnect/requirements.txt
=> specified versions in requirement file

cameraconnect/requirements.txt, cameraconnect/src/cameras.py, cameraconnect/src/main.py, cameraconnect/src/trigger.py, deployment/cameraconnect/docker-compose.yml, deployment/cameraconnect/example_env
Fixes #365 
Multi camera support now available
User specifies camera via mac address, which is written on the back of each camera
Also adjusted the harvester version used
=> 365 assign docker container to camera

AUTHORS, deployment/factorycube-server/values.yaml, docs/content/en/docs/Getting started/usage-in-production/index.md
@all: Please check whether this mention is fine for you
=> Changed authors

docs/content/en/docs/Developers/factorycube-edge/_index.md, docs/content/en/docs/Developers/factorycube-edge/cameraconnect/index.md
Fixes #317 
Start up guide for camera connect still missing
=> 317 add docs to cameraconnect

deployment/factorycube-server/templates/factoryinsight-hpa.yaml
=> Fixed #370

cameraconnect/src/cameras.py
=> 407 throw disconnect error

cameraconnect/src/cameras.py
Fixed #406
adjusted error description since it was outdated
This was caused by the switch from docker-compose to kubernetes
=> adjusted error message to display correct error description

deployment/factorycube-server/templates/mqtttoblob-deployment.yaml
=> Adjusted mqtt-to-blob topic

deployment/factorycube-server/templates/mqtttoblob-deployment.yaml, docs/content/en/docs/Developers/factorycube-server/mqtt-to-blob/index.md, mqtt-to-blob/src/ProductImage.py, mqtt-to-blob/src/main.py
Additionally, added safe JSON parsing
=> Fixed #410

deployment/factorycube-server/values.yaml, mqtt-to-blob/src/main.py
=> Fixed access restrictions between mqtt-to-blob and verneMQ

CODE_OF_CONDUCT.md
=> fix: COC email

cameraconnect/src/cameras.py, docs/content/en/docs/Concepts/mqtt/index.md
=> 423 align mqtt cameraconnect to docs

deployment/factorycube-server/values.yaml
=> Fixes #435

deployment/factorycube-server/templates/timescale-configmap.yaml
=> fixed type conversion product_id in postgres

deployment/factorycube-server/templates/timescale-configmap.yaml
=> 473-dont-allow-null-producttag

deployment/factorycube-server/values.yaml
=> fix: fixed grafana plugin deployment

deployment/factorycube-server/templates/factoryinsight-deployment.yaml, deployment/factorycube-server/values.yaml, golang/cmd/factoryinsight/database.go, golang/cmd/factoryinsight/dataprocessing.go, golang/cmd/factoryinsight/dataprocessing_test.go, golang/cmd/factoryinsight/http.go, golang/go.sum
=> 336-api-digital-shadow

golang/cmd/mqtt-to-postgresql/database.go, golang/cmd/mqtt-to-postgresql/dataprocessing.go, golang/cmd/mqtt-to-postgresql/main.go, golang/cmd/mqtt-to-postgresql/mqtt.go, golang/cmd/mqtt-to-postgresql/queue.go, golang/go.mod, golang/go.sum
=> 52 overwrite data via mqtt

golang/cmd/mqtt-to-postgresql/database.go, golang/cmd/mqtt-to-postgresql/mqtt.go
@Scarjit found and fixed the bug which was probably produced by an incorrect merge
=> repaired merging conflict which broke uniqueProduct in mqtt-to-postgresql

deployment/factorycube-server/templates/factoryinput-pdb.yaml, deployment/factorycube-server/templates/factoryinput-statefulset.yaml, deployment/factorycube-server/templates/vernemq-configmap.yaml, deployment/factorycube-server/values.yaml, deployment/factoryinput/Dockerfile, golang/cmd/factoryinput/http.go, golang/cmd/factoryinput/main.go, golang/cmd/factoryinput/mqtt.go, golang/cmd/factoryinput/queue.go, golang/cmd/grafana-proxy/grafana/api/user/user.go, golang/cmd/grafana-proxy/http.go, golang/cmd/grafana-proxy/main.go
Fixes #54
Also fixes related bugs in grafana-proxy
=> 54 factoryinput

docs/config.toml
=> fix: enabled Algolia Docsearch in docs

deployment/factorycube-server/templates/mqtttopostgresql-statefulset.yaml, golang/cmd/mqtt-to-postgresql/database.go, golang/cmd/mqtt-to-postgresql/mqtt.go, golang/cmd/mqtt-to-postgresql/processAddOrder.go, golang/cmd/mqtt-to-postgresql/processAddParentToChild.go, golang/cmd/mqtt-to-postgresql/processAddProduct.go, golang/cmd/mqtt-to-postgresql/processAddShift.go, golang/cmd/mqtt-to-postgresql/processCountData.go, golang/cmd/mqtt-to-postgresql/processDeleteShiftByAssetIdAndBeginTime.go, golang/cmd/mqtt-to-postgresql/processDeleteShiftById.go, golang/cmd/mqtt-to-postgresql/processEndOrder.go, golang/cmd/mqtt-to-postgresql/processMaintenanceActivity.go, golang/cmd/mqtt-to-postgresql/processModifyProducedPiece.go, golang/cmd/mqtt-to-postgresql/processModifyState.go, golang/cmd/mqtt-to-postgresql/processProductTag.go, golang/cmd/mqtt-to-postgresql/processProductTagString.go, golang/cmd/mqtt-to-postgresql/processRecommendationData.go, golang/cmd/mqtt-to-postgresql/processScrapCount.go, golang/cmd/mqtt-to-postgresql/processScrapUniqueProduct.go, golang/cmd/mqtt-to-postgresql/processStartOrder.go, golang/cmd/mqtt-to-postgresql/processState.go, golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go, golang/cmd/mqtt-to-postgresql/processUniqueProduct.go, golang/cmd/mqtt-to-postgresql/processValueData.go, golang/cmd/mqtt-to-postgresql/processValueString.go, golang/cmd/mqtt-to-postgresql/process_.go, golang/cmd/mqtt-to-postgresql/statements.go, golang/internal/cache.go
added additional check to storeItemsIntoDatabaseUniqueProduct andstoreItemsIntoDatabaseAddOrder, to check if product exists
Fixes #527
=> Fixes MQTT-to-postgres queue locking, if product doesn't exits

cameraconnect/src/trigger.py
Signed-off-by: Lukas Hennies Laptop <lukas.hennies@rwth-aachen.de>
=> fix(critical): indentation error

deployment/factorycube-server/values.yaml
=> 471 grafana-will-not-start-after-reboot-without-internet-connection

docs/static/examples/development.yaml
=> 604 Install script should not continue if encountering an error

deployment/factorycube-server/templates/timescale-configmap.yaml
=> 576 current migrations not according to specs

.github/workflows/check-markdown.yml, docs/content/en/docs/Concepts/integration-with-azure/index.md, docs/content/en/docs/Tutorials/azure/connecting-united-manufacturing-hub-with-azure-iot-hub/index.md
=> fix: markdown-link-check errors #635

golang/cmd/mqtt-to-postgresql/database.go, golang/cmd/mqtt-to-postgresql/processStoredRawMQTT.go, golang/cmd/mqtt-to-postgresql/statements.go
Reduces the impact of #660 
#660 should remain open until confirmation of the fix in production
=> fix: This aims to fix the long wait time observed in #660 by reducing the queue timeout on error.

.github/dependabot.yml
This prevents dependabot from creating labels, that are already existing.
=> fix: Fixes dependabot labels

deployment/factorycube-server/Chart.yaml, deployment/factorycube-server/templates/_helpers.tpl, deployment/factorycube-server/templates/kafka-statefulset.yaml, deployment/factorycube-server/values.yaml
=> feat: Add Kafka to Kubernetes

golang/go.sum
=> fix: Fixed Kafka-to-blob not building

deployment/factorycube-server/values.yaml
=> fix: kafka statefulset not starting

deployment/factorycube-server/templates/kafka-statefulset.yaml, deployment/factorycube-server/values.yaml
Hopefully finally fixes the kafka startup problem
=> fix: manually overwrite ALLOW_PLAINTEXT_LISTENER

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This pull requests adds an pull request template.
Fixes #708
I'v rendered the markdown, to check for syntax errors
=> feat: Added pull request template

.githooks/config.json, .githooks/functions/git.py, .githooks/functions/helper.py, .githooks/functions/ilib.py, .githooks/functions/libhelmlint.py, .githooks/functions/libyamllint.py, .githooks/functions/log.py, .githooks/pre-push, CONTRIBUTING.md, test.yaml
This pull request provides an pre-push hook.
The hook checks for changes to .yaml files and Chart.yaml files.
If a change is detected or the branch has no upstream, then it will check the changed files (all files if no upstream) and fail if there are any errors.
All [yamllint rules](https://yamllint.readthedocs.io/en/stable/rules.html) can be configured inside the config.json
<details>
<summary>Example config.json</summary>
````
{
"yamllint": {
"allow": [
],
"warn": [
"line-length",
"comments",
"empty-lines",
"trailing-spaces"
]
}
}
````
</details>
Fixes #710
I executed the hook before pushing this change.
I changed and committed local files, then run the hook
The correctness of test results rely on external tools ([helm](https://helm.sh/docs/helm/helm_lint/) & …
=> feat: add git hooks

deployment/kafka-init/Dockerfile, golang/cmd/kafka-init/kafka.go, golang/cmd/kafka-init/main.go
This pull requests adds an microservice to create Kafka topics if they don't exists.
Fixes #728
=> feat: kafka init container

README.md
Fixes #663
Currently blocked by [an internal discussion](https://github.com/united-manufacturing-hub/vision-mission-values-and-working-mode/issues/1)
=> docs: new project description

deployment/factorycube-server/templates/vernemq-configmap.yaml, golang/cmd/mqtt-kafka-bridge/main.go, golang/cmd/mqtt-kafka-bridge/mqtt.go
This pull request fixes the issue, that mqtt-kafka-bridge can't connect to our mqtt broker
=> fix: No client id & username

golang/cmd/mqtt-kafka-bridge/kafka.go, golang/cmd/mqtt-kafka-bridge/mqtt.go
Added a better description, when invalid json is send to mqtt-kafka-bridge
Fixes #738
Image builds locally
=> fix: added better json error message

README.md, golang/cmd/mqtt-kafka-bridge/kafka.go, golang/cmd/mqtt-kafka-bridge/mqtt.go, golang/internal/cache.go
This fixes #742 by restarting the application until the connection can be re-established.
=> fix: mqtt kafka bridge not re subscribing after mqtt disconnection

golang/internal/ioddfinder.go, golang/internal/ioddfinder_test.go
This pr adds an helper function to download iodd files from iodd finder.
Iv run goland unit test for 2 devices from different vendors
=> feat: Added helper function to download iodd files from https://ioddfinder.io-link.com/

golang/internal/ioddfinder.go, golang/internal/ioddfinder_test.go
This pr introduces an exponential backoff behavior to the download of iodd files.
=> feat: Iodd download helper

docs/content/en/docs/Concepts/datamodel/_index.md, docs/content/en/docs/Concepts/datamodel/kafka/index.md
This pr fixes #763 by adding documentation for the default retention settings.
=> feat: Added documentation for current kafka retention settings

.githooks/functions/helper.py, .githooks/functions/libdockerlint.py, .githooks/functions/libgovet.py, .githooks/functions/libstaticcheck.py, .githooks/pre-push
=> feat: Improve code quality checking lints

golang/cmd/factoryinput/http.go, golang/cmd/factoryinsight/http.go
Currently using "jeremy" as user in factoryinsight/factoryinput bypasses the authentication.
Fixes #785 
- No tests
=> fix: setting user to jeremy bypasses user authentication in factoryinsight

deployment/factorycube-server/templates/mqtt-kafka-bridge-deployment.yaml
MQTT_CERTIFICATE_NAME not correct
Fixes #740
not tested
=> fix: MQTT_CERTIFICATE_NAME env

docs/content/en/docs/Developers/factorycube-server/mqtt-kafka-bridge/index.md
This pr adds documentation for mqtt-kafka-bridge
Fixes #832
=> feat: Added docs for mqtt-kafka-bridge

README.md
Added technical information to README
Fixes #780
no test needed
=> feat: added technical information to README

deployment/united-manufacturing-hub/templates/sensorconnect-deployment.yaml
This pr fixes a merge issue, from the v0.8.0 release, which results in sensorconnect not starting.
Fixes #869
=> fix: fixed incorrect mount path in sensorconnect.

CONTRIBUTING.md
Adjusted Contributing to
- use new branch scheme, e.g., fix/234/short-description-of-fix
- removed staging. we will now use only main
=> docs: adjusted CONTRIBUTING

deployment/kafka-debug/Dockerfile, deployment/kafka-init/Dockerfile, deployment/kafka-to-blob/Dockerfile, deployment/mqtt-kafka-bridge/Dockerfile, deployment/united-manufacturing-hub/values.yaml, golang/cmd/kafka-debug/kafka.go, golang/cmd/kafka-debug/main.go, golang/cmd/kafka-init/kafka.go, golang/cmd/kafka-init/main.go, golang/cmd/kafka-to-blob/kafka.go, golang/cmd/kafka-to-blob/main.go, golang/cmd/mqtt-kafka-bridge/kafka.go, golang/cmd/mqtt-kafka-bridge/main.go, golang/internal/kafka.go, golang/kafka_helper/kafka.go
This pr merges duplicate kafka code
Fixes #915
=> Merged duplicate kafka code

docs/static/examples/development.yaml
This pr adds KafkaBridge to the development.yaml and changes key names in accordance with the current values.yaml
=> feat: Added kafkaBridge to development.yaml and updated keys

deployment/helm-repo/index.yaml
Fixed error in Helm repo
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Kubernetes Version: 
* Helm Version:
* Hardware:
=> fix: helm repo

golang/cmd/kafka-to-postgresql/highIntegrityProcessor.go
This pr improves the debugging experience in kafka-to-postgres
=> Added better errors to kafka-to-postgres

deployment/united-manufacturing-hub/templates/kafkabridge-deployment.yaml, deployment/united-manufacturing-hub/values.yaml, docs/content/en/docs/Developers/united-manufacturing-hub/kafka-bridge/index.md, golang/cmd/kafka-bridge/main.go, golang/cmd/kafka-to-postgresql/main.go
This pr fixes varios issues with kafka-to-post.
It also provides an easier method for configuring it. (Now uses a YAML map instead of JSON string)
This new functionality is also documented.
Fixes #J30
=> Fix kafka bridge issues

golang/cmd/kafka-bridge/kafka.go, golang/cmd/kafka-bridge/main.go
This pr attempts to fix #1000 by improving the shutdown logic
Fixes #1000
=> Added check for double shutdown and added finite timeout for channel checking

golang/cmd/mqtt-kafka-bridge/main.go
This pr improves the MQTT->Kafka topic conversion by trimming the incoming MQTT topic string and then matching it against a regex of all valid Kafka topics
Fixes #998
=> Improved MQTT->Kafka topic parsing, by trimming the string and matching against regex.

golang/cmd/factoryinsight/database.go, golang/cmd/factoryinsight/dataprocessing.go, golang/cmd/factoryinsight/dataprocessing_shifts.go, golang/cmd/factoryinsight/http.go
This pr replaces otel with zap.
We currently do not have the infrastructure to use otel
=> feat: replaced otel with zap

deployment/united-manufacturing-hub/values.yaml, golang/cmd/kafka-to-postgresql/main.go
This pr fixes an incorrect topic subscription and infinitive shutdown times
=> fix: Fixed incorrect topic subscription and infinitive shutdown

.github/workflows/docker-image-kafka-state-detector.yml, deployment/kafka-state-detector/Dockerfile, deployment/united-manufacturing-hub/templates/kafkabridge-deployment.yaml, golang/cmd/kafka-bridge/TopicMapProcessors.go, golang/cmd/kafka-bridge/main.go, golang/cmd/kafka-state-detector/main.go
This pr adds missing dockerfile and workflow for state microservice
=> Added missing workflow

deployment/united-manufacturing-hub/templates/kafka-state-detector.yaml, deployment/united-manufacturing-hub/values.yaml, golang/cmd/kafka-state-detector/main.go
=> fix: exposed ANOMALY_ENABLED and ACTIVITY_ENABLED env vars

golang/cmd/kafka-init/kafka.go
=> fix: fixed panic if topic exists

golang/cmd/kafka-state-detector/main.go
Anomaly part of state detector was missing bootstrap server
=> No bootstrap server in anomaly

golang/cmd/kafka-init/main.go
Fixes kafka bridge not shutting down
=> fix: fixed init not shutting down

golang/cmd/kafka-bridge/TopicMapProcessors.go, golang/internal/kafkaSharedTypes.go
=> fix: set producer partition to any.

docs/content/en/docs/Concepts/mqtt/index.md
Fixes J43 (documenting sensorconnect topics)
=> docs: adjusted sensorconnect docs

golang/internal/topicValidator.go
=> fix: set last match group optional for raw

docs/static/examples/development.yaml
This fixes a small spelling mistake which casues development.yaml to not be working
Not tested
=> fix: development yaml not working

golang/cmd/kafka-to-postgresql/pxAddProduct.go
=> Fixed crash in pxAddOrder

golang/cmd/kafka-to-postgresql/_pxTemplate.go, golang/cmd/kafka-to-postgresql/highIntegrityProcessor.go, golang/cmd/kafka-to-postgresql/pxAddOrder.go, golang/cmd/kafka-to-postgresql/pxAddParentToChild.go, golang/cmd/kafka-to-postgresql/pxAddProduct.go, golang/cmd/kafka-to-postgresql/pxAddShift.go, golang/cmd/kafka-to-postgresql/pxCount.go, golang/cmd/kafka-to-postgresql/pxEndOrder.go, golang/cmd/kafka-to-postgresql/pxProductTag.go, golang/cmd/kafka-to-postgresql/pxProductTagString.go, golang/cmd/kafka-to-postgresql/pxScrapCount.go, golang/cmd/kafka-to-postgresql/pxScrapUniqueProduct.go, golang/cmd/kafka-to-postgresql/pxStartOrder.go, golang/cmd/kafka-to-postgresql/pxState.go, golang/cmd/kafka-to-postgresql/pxUniqueProduct.go
This pr adds better error logging for putback messages.
These errors will appear in the header of kafka messages.
=> Better error logging for putback messages

golang/cmd/barcodereader/main.go
This pr fixes a nullpointer in sensorconnect
Fixes #J69
=> Fixed barcodereader null pointer

deployment/united-manufacturing-hub/templates/nodered-statefulset.yaml, deployment/united-manufacturing-hub/values.yaml
Removed init plugin installer, flows are not removed
Fixes #1056
=> Removed default node-red plugin installer

deployment/united-manufacturing-hub/values.yaml
This pr fixes a strange error, with our values.yaml, that appeared after 3 months.
=> Grafana install error

.gitignore
This pr hides internal values and development yaml file
=> hide internal values and development yaml files

deployment/united-manufacturing-hub/templates/barcodereader/deployment.yaml
=> fix: fixed barcodereader template tried to pull map instead of string

golang/cmd/kafka-to-postgresql/pxAddShift.go
=> fix: kafka-to-postgres to able to add shifts

deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/deployment.yaml, deployment/united-manufacturing-hub/values.yaml
=> incorrect cert name

golang/cmd/factoryinsight/database.go, golang/cmd/kafka-init/kafka.go, golang/cmd/kafka-init/main.go, golang/internal/kafka.go
Fixes a bug, where an nil value for scrap would be cast to an float64
=> Incorrect cast from nullptr to float64

golang/cmd/mqtt-kafka-bridge/kafka.go
This pr fixes an issue, where messages would get stuck in MQTT-Kafka-bridge and still being confirmed on the kafka broker
Fixes #1145
=> Added check preventing consuming more kafka messages if >= 100 are already stuck

golang/cmd/sensorconnect/processSensorData.go
This pr demotes a warning to an debug message, preventing log spam
Fixes #1146 
=> Demoted port disconnection message to debug

golang/cmd/kafka-to-postgresql/highIntegrityProcessor.go
This pr fixes an error from a previous merge
=> ModifyProducesPieces -> ModifyProducedPieces

docs/content/en/docs/Developers/publish-new-version/index.md
This pr fixes 1081 by setting --devel to code formatted text
Fixes #1081
=> Prevent hugo from misinterpreting devel flag

deployment/united-manufacturing-hub/templates/barcodereader/deployment.yaml
This pr fixes an spelling mistake
=> Correct barcodereader deployment

golang/cmd/mqtt-kafka-bridge/mqtt.go
This pr fixes an issue, where it isn't shutting down, even if the connection to the mqtt broker is lost.
=> Shutdown if mqttClient ist disconnected

golang/internal/cache.go
This pr adds better error messages for redis failures
=> feat: added better debug messages for redis failures

golang/cmd/factoryinsight/database.go, golang/cmd/factoryinsight/http.go, golang/pkg/datamodel/structs.go
This PR shows all orders that have not started yet
Fixes  #1195 
Tested on UMH development with various datasets.
=> feat: added unstartedOrders to factoryinsight

.github/PULL_REQUEST_TEMPLATE.md
I shortened the checklist and put in changelog and upgrade tutorials in it.
=> Shortened the checklist

deployment/custom-microservice-tester/Dockerfile, deployment/united-manufacturing-hub/templates/customMicroservices/service.yaml, deployment/united-manufacturing-hub/templates/customMicroservices/statefulset.yaml, deployment/united-manufacturing-hub/values.yaml, golang/cmd/custom-microservice-tester/main.go
This pr adds a custom-microservice tester
This is a test itself
=> feat: Added  custom microservice tester

golang/cmd/custom-microservice-tester/main.go
This pr fixes a minor issue with the web handler in our cm test service.
=> fix: fixed web handler for example service

golang/cmd/kafka-to-postgresql/pxProcessValue.go, golang/cmd/kafka-to-postgresql/pxProcessValueString.go
This pr promotes parsing and unmarshalling errors in PV, to be putback.
Fixes #1225
=> feat: enabled putback for unparsable messages

deployment/united-manufacturing-hub/templates/customMicroservices/persistentvolumeclaim.yaml, deployment/united-manufacturing-hub/templates/customMicroservices/service.yaml, deployment/united-manufacturing-hub/templates/customMicroservices/statefulset.yaml, deployment/united-manufacturing-hub/values.yaml
This pr introduces a switch, turning off custom microservices by default
Fixes #1227
=> feat: Added enabled switch

golang/internal/kafkaTopics.go
This pr allows mqtt->kafka bridge to send processValueStrings
Thanks to TexControl @ discord for finding this bug
=> fix: added PVS to mqtt->kafka regex

docs/static/examples/development.yaml
Adds a single echo to the end of the install script, notifying the user, that he can press ENTER to get the linux login screen
=> feat: hint for login screen

golang/cmd/barcodereader/main.go, golang/cmd/custom-microservice-tester/main.go, golang/cmd/factoryinput/http.go, golang/cmd/factoryinput/main.go, golang/cmd/factoryinput/mqtt.go, golang/cmd/factoryinsight/main.go, golang/cmd/grafana-proxy/grafana/api/user/orgs.go, golang/cmd/grafana-proxy/grafana/api/user/user.go, golang/cmd/grafana-proxy/http.go, golang/cmd/grafana-proxy/main.go, golang/cmd/kafka-bridge/main.go, golang/cmd/kafka-debug/main.go, golang/cmd/kafka-init/main.go, golang/cmd/kafka-state-detector/main.go, golang/cmd/kafka-to-blob/main.go, golang/cmd/kafka-to-postgresql/main.go, golang/cmd/mqtt-bridge/main.go, golang/cmd/mqtt-bridge/mqtt.go, golang/cmd/mqtt-kafka-bridge/main.go, golang/cmd/mqtt-kafka-bridge/mqtt.go, golang/cmd/sensorconnect/downloadPortModeData.go, golang/cmd/sensorconnect/downloadSensorData.go, golang/cmd/sensorconnect/iolinkDeviceFinder.go, golang/cmd/sensorconnect/main.go, golang/cmd/sensorconnect/mqtt.go, golang/cmd/sensorconnect/processIoddFiles.go, golang/cmd/sensorconnect/processIoddFiles_test.go, golang/cmd/sensorconnect/processSensorData_test.go, golang/internal/ioddfinder.go
There where some merges, during the time the new pre-push pr was open, therefor it merged some incompatible code, which is fixed here.
Also there was a golangci-lint upgrade in there, which introduced new tests.
=> Fix test issues from merges during pr being open

golang/internal/kafkaTopics.go, golang/internal/kafkaTopics_test.go
This pr adds new regexes for the new datamodel and deprecates the old ones.
Fixes #1283 
Syntax match:
https://regex101.com/r/iTHLpB/
Custom match:
https://regex101.com/r/Fqeu2Q
Raw match:
https://regex101.com/r/nBQUTv
Standard match:
https://regex101.com/r/VSFrSy/
=> Check regex for new datamodel

deployment/helm-repo/k3d/k3d-umh-config.yaml
Add config file for k3d cluster to `repo.umh.app/k3d`
Deployed k3d cluster
=> feat: add config file for k3d cluster

deployment/united-manufacturing-hub/templates/automigrate/deployment.yaml
This pr fixes an incorrect helm template for automigrate
=> fix: automigrate needs superuser permissions

deployment/united-manufacturing-hub/values.yaml
This pr fixes all occurrences of the old datamodel in our values.yaml
Fixes #1282 
=> fix: updated values for new datamodel

golang/cmd/factoryinsight/v2/services/service-tags.go
Fixes an issue, where 0000 where not removed
=> fix: remove additional zeros

cameraconnect/requirements.txt, deployment/united-manufacturing-hub/templates/_helpers.tpl, deployment/united-manufacturing-hub/templates/packmlmqttsimulator/deployment.yaml, deployment/united-manufacturing-hub/values.yaml
Adds a dockerpod of our newly forked microservice [PACKML-MQTT Simulator](https://github.com/united-manufacturing-hub/PackML-MQTT-Simulator). Visit the fork for documentation
Deployed the stack and tested if the packml sim is responsive. Sebastian is currently doing deeper testing of the functionality by tinkering node-RED flows for the simulator
Enter here your text for the changelog (or fill it out directly in Notion if you are internal)
=> feat: first packmlmqtt sim implementation

deployment/build_and_push_with_tag.ps1
Add an explicit error message in case of a push failure
Used it
=> fix: add explicit error in case of push failure

deployment/united-manufacturing-hub/Chart.yaml
Timescales helm repo URL has changed. (See https://github.com/timescale/helm-charts)
=> feat: updated timescale url

golang/cmd/factoryinsight/v2/controllers/controller-tags.go, golang/cmd/factoryinsight/v2/models/dto-tags.go, golang/cmd/factoryinsight/v2/services/common.go, golang/cmd/factoryinsight/v2/services/service-tags.go, golang/cmd/factoryinsight/v2/services/service-tree.go
Feature Added processValueStrings
Fixes https://github.com/united-manufacturing-hub/umh-datasource-v2/issues/12
- [ x] New feature (non-breaking change which adds functionality)
=> feat/12/Add processValueStrings

golang/internal/kafka.go
This pr makes our services automatically create the probeTopic.
Fixes #1412
=> feat: each microservice will now attempt to create the probeTopic

deployment/united-manufacturing-hub/values.yaml
Small fix for kafkabridge
Fixes #1386
=> Added missing space between list and comment

deployment/united-manufacturing-hub/templates/sensorconnect/deployment.yaml
This PR fixes some typos in the deployment configuration of sensorconnect
Fixes #1452 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Fix sensorconnect not being able to activate

golang/cmd/factoryinsight/v2/services/service-tree.go
This pr fixes an issue from Zendesk
=> Additional safeguards against null pointers

README.md
=> Fix: Change license badge

deployment/united-manufacturing-hub/templates/metrics/job.yaml
=> Missing $ in loop expression

golang/cmd/grafana-proxy/http.go
This change adds an endpoint for nodered HTTP api to grafana proxy.
Auth is done by nodered itself.
This feature was requested on our community discord.
=> Grafana proxy nodered endpoint

deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1051
=> Fix `get_asset_ids` function creation statement

golang/cmd/kafka-to-postgresql-v2/postgresql/postgresql.go, golang/cmd/kafka-to-postgresql-v2/worker/worker.go
Fixes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1083
=> Fix timescale time problem

deployment/united-manufacturing-hub/values.yaml, golang/cmd/sensorconnect/main.go
Fix https://github.com/united-manufacturing-hub/MgmtIssues/issues/1086
Documentation PR: https://github.com/united-manufacturing-hub/umh.docs.umh.app/pull/184
=> Increase lower polling rate to 10Hz

.github/workflows/build-docker-images.yml, go.work.sum, golang/cmd/kafka-to-postgresql-v2/kafka/kafka.go, golang/cmd/kafka-to-postgresql-v2/main.go, golang/cmd/kafka-to-postgresql-v2/worker/worker.go, golang/go.mod, golang/go.sum, golang/vendor/github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper-2/pkg/kafka/consumer/redpanda/client.go, golang/vendor/github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper-2/pkg/kafka/consumer/redpanda/consumer_group_handler.go, golang/vendor/modules.txt
Here are the changes done to the wrapper itself:
https://github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper-2/compare/v1.6.23...v1.9.0
Major changes:
- Sarama kafka will now re-open the full connection
- Sarama kafka will now randomize the instanceId, preventing [KIP-345](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances)
=> feat: Updated sarama kafka wrapper, allowing topic changes during runtime

.github/workflows/build-docker-images.yml, .idea/.gitignore, .idea/united-manufacturing-hub.iml, deployment/grafana-umh/Dockerfile
Partly fixes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1511
=> Added permissions and login for gh enterprise

deployment/united-manufacturing-hub/values.yaml
Fixes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1601
We do not use this image, but our tests are failing because it is referenced
=> use newer os-shell

deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
New tables for:
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1658
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1659
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1660
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1661
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1662
=> New tables for _analytics

deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
This pr fixes a problem where helm cannot deploy this version due to a parsing error
=> Fix parser error in helm

.github/workflows/run_go_tests_k2pg-v2.yaml, deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-state.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics_test.go, golang/cmd/kafka-to-postgresql-v2/shared/structs.go, golang/cmd/kafka-to-postgresql-v2/worker/analytics.go, golang/cmd/kafka-to-postgresql-v2/worker/analytics_test.go, golang/cmd/kafka-to-postgresql-v2/worker/worker.go
Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1662
=> [#1662 (0)] state in kafka-to-postgresql-v2

golang/cmd/kafka-to-postgresql-v2/helper/helper.go, golang/cmd/kafka-to-postgresql-v2/kafka/kafka.go, golang/cmd/kafka-to-postgresql-v2/kafka/kafka_mock.go, golang/cmd/kafka-to-postgresql-v2/main.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-product-type.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-product.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-shift.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-state.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-work-order.go, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics_test.go, golang/cmd/kafka-to-postgresql-v2/postgresql/historian.go, golang/cmd/kafka-to-postgresql-v2/postgresql/lru.go, golang/cmd/kafka-to-postgresql-v2/postgresql/postgresql.go, golang/cmd/kafka-to-postgresql-v2/postgresql/postgresql_mock.go, golang/cmd/kafka-to-postgresql-v2/postgresql/postgresql_test.go, golang/cmd/kafka-to-postgresql-v2/shared/structs.go, golang/cmd/kafka-to-postgresql-v2/worker/analytics.go, golang/cmd/kafka-to-postgresql-v2/worker/worker.go, golang/cmd/kafka-to-postgresql-v2/worker/worker_test.go
Based on https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/1760
=> [#1662 (2)] kafka-to-postgresql-v2 various bug fixes

deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml, golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-product.go, golang/cmd/kafka-to-postgresql-v2/shared/structs.go, golang/cmd/kafka-to-postgresql-v2/worker/analytics.go
The user should send external_product_type_id and not external_product_id (this doesn't exist)
=> [#1662 (7)] Clarify external_product_type_id vs external_product_id

golang/cmd/kafka-to-postgresql-v2/worker/topicProcessor.go, golang/cmd/kafka-to-postgresql-v2/worker/topicProcessor_test.go, golang/cmd/kafka-to-postgresql-v2/worker/worker_test.go
This fix modifies the regex to set the dot and the tag group following it as optional.
=> Set tag group as optional

golang/cmd/kafka-to-postgresql-v2/worker/historian.go, golang/cmd/kafka-to-postgresql-v2/worker/historian_test.go, golang/cmd/kafka-to-postgresql-v2/worker/topicProcessor_test.go
Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1765
=> Don't deduplicate tags

deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
https://www.postgresql.org/docs/current/xfunc-volatility.html
This pr adds some functions that are more performant (tested at around ~30x faster, but this varies with amount of requested rows)
=> ENG-683 stable and immutable variants

deployment/united-manufacturing-hub/templates/bridges/kafka-to-mqtt/historian/configmap.yaml, deployment/united-manufacturing-hub/templates/bridges/kafka-to-mqtt/historian/deployment.yaml, deployment/united-manufacturing-hub/templates/bridges/kafka_to_postgres/historian/configmap.yaml, deployment/united-manufacturing-hub/templates/bridges/kafka_to_postgres/historian/deployment.yaml, deployment/united-manufacturing-hub/templates/bridges/mqtt-to-kafka/historian/deployment.yaml
See also https://stackoverflow.com/a/77633748/3160474
=> ENG-1831 add ep config for bridges & dont start kafka from oldest

umh-core/pkg/communicator/actions/deploy-dataflowcomponent.go, umh-core/pkg/communicator/actions/deploy-dataflowcomponent_test.go, umh-core/pkg/communicator/actions/edit-dataflowcomponent.go, umh-core/pkg/communicator/actions/edit-dataflowcomponent_test.go, umh-core/pkg/models/action_models.go
The problem was that the frontend sends the yaml inject part as `rawYAML` and not as `inject`. The tests have been updated and the parsing is fixed now
=> [ENG-3022] Fix YAML Inject Handling

umh-core/pkg/service/topicbrowser/parse.go
Fixes decoding by allocation compressed lenght x 255 instead of x4/x8.
This seems to be the upper bound according to https://stackoverflow.com/questions/25740471/lz4-library-decompressed-data-upper-bound-size-estimation
=> Fix LZ4 decode for highly compressible data.

umh-core/pkg/communicator/pkg/subscriber/subscribers.go, umh-core/pkg/communicator/router/router.go, umh-core/pkg/communicator/subscribers/registry.go, umh-core/pkg/communicator/subscribers/registry_test.go, umh-core/pkg/models/action_models.go, umh-core/test/communicator/subscribe_and_receive_test.go
This PR also switches to a value type inside the expiremap, which seems more ideomatic, regarding the small footprint of SubscriberData
=> [ENG-3120] Resubscription Logic

umh-core/pkg/communicator/actions/deploy-streamprocessor.go, umh-core/pkg/communicator/pkg/generator/generator.go, umh-core/pkg/models/action_models.go
=> Stream Processor ignore health check
