- cameraconnect/src/cameras.py
- docs/content/en/docs/Concepts/mqtt/index.md
Fixes #409
1. added image_id to mqtt message 
2. adjusted docs
Serial number of cameras will not be used anymore, only mac address
> 409 add cameraconnect mqtt message

- .githooks/functions/libhelmlint.py
- .githooks/functions/libyamllint.py
While refactoring i have moved the init of the file list inside the has_upstream check, this is incorrect.
> fix: lint when no upstream is present

- deployment/factorycube-server/templates/timescale-configmap.yaml
Our test data inserted products, while also setting there ID.
Doing this, won't change the postgres sequence, resulting in errors, when inserting new values afterwards.
Fixes #771 
I have created a local table, with an id (serial) and name.
Select currect sequence ID -> 1
`SELECT last_value FROM test_table_id_seq;`
Insert 3 times by specifing the id to insert at.
`INSERT INTO test_table (id,name) VALUES (1, 'test1');`
`INSERT INTO test_table (id,name) VALUES (2, 'test2');`
`INSERT INTO test_table (id,name) VALUES (3, 'test2');`
Select currect sequence ID -> 1
`SELECT last_value FROM test_table_id_seq;`
Select currect sequence ID -> 1
`SELECT last_value FROM test_table_id_seq;`
Insert 3 times by specifing the id to insert at.
`INSERT INTO test_table (name) VALUES ('test1');`
`INSERT INTO …
> fix: default values for productTable are inserted incorrectly

- deployment/factorycube-server/templates/factoryinput-pdb.yaml
- deployment/factorycube-server/templates/factoryinsight-hpa.yaml
- deployment/factorycube-server/templates/factoryinsight-pdb.yaml
- deployment/factorycube-server/templates/kafkatoblob-pdb.yaml
- deployment/factorycube-server/templates/mqtt-kafka-bridge-pdb.yaml
- deployment/factorycube-server/templates/mqtttoblob-pdb.yaml
- deployment/factorycube-server/templates/mqtttopostgresql-pdb.yaml
This PR removes deprecation warnings, by upgrading to the new pod apiVersions
Fixes #807 
> fix: fixed deprecation warnings

- deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge-deployment.yaml
- golang/cmd/mqtt-kafka-bridge/hash.go
- golang/cmd/mqtt-kafka-bridge/main.go
Fixes #876 by removing redis requirement from mqtt-kafka-bridge
> Removed redis requirement from mqtt-kafka-bdirge

- golang/cmd/mqtt-to-postgresql/main.go
Fixes #878 by moving SetupMQTT after queue initialization
> Moved mqtt setup after queue initialization

- barcodereader/src/main.py
- deployment/united-manufacturing-hub/templates/barcodereader-Deployment.yaml
Fixes #879
Also fixes an error occuring due to merger of MQTT url and port, while keeping backward compatibility.
> Fixes barcodereader not starting

- docs/content/en/docs/Tutorials/united-manufacturing-hub/working-with-helm-and-lens/index.md
This pr adds ```helm repo update``` and restarting Lens to the lens usage tutorial
Fixes #912
> Added missing documentation step when using lens

- deployment/united-manufacturing-hub/templates/kafkatopostgresql-deployment.yaml
This pr adds an and operator to check if datastorage (postgres) and kafka are enabled, before starting kafka-to-postgresql
Fixes #982
> Added and operator to only start kafka-to-postgresql if datastorage & kafka are enabled

- deployment/united-manufacturing-hub/values.yaml
This pr reduces the log.segment.bytes to 10MiB and the log.retention.bytes to 500MiB.
Further reduction of log.retention.bytes might be nessecary if disk space is an issue.
The current log.segment.bytes would hold ~100k messages per log.
Fixes #989
> Log deletion in kafka cannot work properly

- deployment/united-manufacturing-hub/templates/kafkabridge-deployment.yaml
- deployment/united-manufacturing-hub/values.yaml
- golang/cmd/kafka-bridge/kafka.go
- golang/cmd/kafka-debug/kafka.go
- golang/cmd/kafka-to-blob/kafka.go
- golang/cmd/kafka-to-postgresql/database.go
- golang/cmd/kafka-to-postgresql/highIntegrityProcessor.go
- golang/cmd/kafka-to-postgresql/highThroughputProcessor.go
- golang/cmd/kafka-to-postgresql/kafkaSharedTypes.go
- golang/cmd/kafka-to-postgresql/main.go
- golang/cmd/mqtt-kafka-bridge/kafka.go
This pr redirects messages, which either fail >= 50 times or (>= 2 times and are older then 5 minutes).
It also adds an sleep, if no new messages are available for processing by any Kafka microservices, preventing high idle loads.
Also adds an init container to kafka-bridge allowing for creating of dummy topics, to prevent crashes
> Redirect failing messages to there own queue, added init container for kafka-bridge.

- deployment/united-manufacturing-hub/templates/timescale-configmap.yaml
This pr decreases lookup times for distinct queries on processValueTable and processValueStringTable from ~5s to 50-200ms on 10m datasets.
> Added index for processValueTable & processValueStringTable on valuename to massively increase speed

- golang/cmd/sensorconnect/iolinkDeviceFinder.go
Fixes #1072 by providing a better a error message and then cleanly restarting
> Better error handling for create topic timeout

- deployment/united-manufacturing-hub/templates/kafkatopostgresql/deployment.yaml
- deployment/united-manufacturing-hub/values.yaml
This pr adds an init container for kafkatopostgresql, to prevent crashes on startup, by suppling a dummy topic for both workers.
> feat: Init container for kafkatopostgresql

- deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/deployment.yaml
mqtt-kafka-bridge fails to startup in SSL mode, due to missing volume
> fix: mqtt-kafka-bridge not starting with kafka mtls

- deployment/united-manufacturing-hub/templates/kafkabridge/deployment.yaml
- docs/static/examples/development.yaml
In the last pre-release the url of the repo was incorrect.
Also it hat duplicate volumes definition in kafkabridge
> Fixes incorrect url in install script and duplicate volumes definition for kafkabridge

- golang/cmd/factoryinsight/database.go
- golang/cmd/factoryinsight/dataprocessing_shifts.go
- golang/internal/constants.go
This pr fixes an issue, where the wrong time is returned (time.Time{} instead of the unix epoch)
go epoch will return a negative number, confusing grafana. (https://github.com/golang/go/issues/10906)
Fixes #1143
> Return unix epoch instead of go epoch

- golang/cmd/factoryinsight/dataprocessing_shifts.go
This pr fixes an issue, where the timestampBegin and timestampEnd where not correctly initialized, resulting in failed tests
Fixes #1143
> Initialized begin and end time to unix epoch to pass tests

- deployment/united-manufacturing-hub/templates/factoryinput/statefulset.yaml
- deployment/united-manufacturing-hub/templates/factoryinsight/deployment.yaml
- deployment/united-manufacturing-hub/templates/grafanaproxy/deployment.yaml
- deployment/united-manufacturing-hub/templates/kafkatopostgresql/deployment.yaml
- deployment/united-manufacturing-hub/templates/mqtttopostgresql/statefulset.yaml
- deployment/united-manufacturing-hub/templates/nodered/statefulset.yaml
- deployment/united-manufacturing-hub/values.yaml
This pr replaces startup delays with startup probes, in accordance with https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
This will allow for slow container startup, but also for fast issue detection and killing of the container, in case of unresponsiveness.
Fixes #1161
> Replace initialDelay with startup probe

- golang/pkg/datamodel/stateModelString.go
I added the Turkish language to make the dashboars more understandable in Turkey. In this way, employees can monitor the machine's status, etc. can see in the local language.
It's not a merge I did against a problem. I just added the translation of the Turkish language. For this, I set up an else if structure between the existing if - else structure.
I haven't done any testing.
**Test Configuration**:
* Kubernetes Version: 
* Helm Version:
* Hardware:
> Turkish Language Support

- golang/cmd/kafka-init/main.go
Fixed wrong usage of `log` object and replaced with the correct `zap.S().Infof()` in `kafka-init/main.go`
*not needed*
*not needed*
*not needed*
*not needed*
> fix: resolve codecov checks

- golang/cmd/kafka-to-blob/main.go
- golang/cmd/kafka-to-postgresql/main.go
- golang/cmd/mqtt-kafka-bridge/main.go
- golang/go.mod
- golang/internal/kafka.go
- golang/internal/kafkaMessageProcessing.go
- golang/internal/kafkaSharedTypes.go
Adds a specific topic to which all consumer services subscribe. Messages in this topic contain the names of any new topics created by publishers, and consumers will automatically add the new topics to their subscription list.
In this way we can reduce the time needed to add a new topic to a couple of seconds, instead of relying on the `metadata.max.age.ms` parameter (#1223)
Fixes #1253 
Full deployment of the stack on my local minikube cluster
Added push-based detection of new topics
*not needed*
> feat: add push based subscription for new topics

- golang/internal/kafka.go
Rename the topic for KafkaTopicProbeConsumer from `umh.kafka.topic.created` to `umh.v1.kafka.newTopic`. This way it will fit the new convention that its being discussed for the rework of the datamodel
Fixes #1269
*not needed*
*not needed*
*not needed*
> Feat: change topic name for KafkaTopicProbeConsumer

- golang/cmd/kafka-to-postgresql/pxProcessValue.go
This pr adds functionality to kafka-to-postgres, to try parse non-float64 values as float64. (for example strings containing floats).
It also increases the log level for incorrect messages to WARN
See: 
- https://go.dev/ref/spec#Integer_literals
- https://go.dev/ref/spec#Floating-point_literals
- https://forum.golangbridge.org/t/potential-bug-in-strconv-parsefloat/29079
Fixes #1266
> Try convert string to float64 in kafka-to-postgresql

- deployment/united-manufacturing-hub/templates/mqtt-kafka-bridge/deployment.yaml
This pr removes a duplicate volumeMounts mapping inside mqtt-kafka-bridge
Fixes #1416
> Removed duplicate mapping in mqtt-kafka-bridge

- golang/cmd/factoryinsight/v1/database.go
- golang/cmd/factoryinsight/v1/dataprocessing.go
- golang/cmd/factoryinsight/v1/http.go
Fixes #92 #90 #89 #88 #87 #86 #97 #96 #98
now returns the timestamps in RFC3339. It converts an int64 to unix to RFC3339
Conversion was tested separately and converts correctly.
**Note**: The equation (previousTimestamp.UnixNano()/(int64(time.Millisecond)/int64(time.Nanosecond))) makes no sense mathematically; it is off by a factor of 1000  -> Maybe intended?
> inconsistency #92 ReturnTimestampsInRFC3339InProductionSpeed

- golang/cmd/factoryinsight/v1/database.go
This pr hotfixes a time bug for v1 api in factoryinsight.
It was already deployed to 0.9.10's docker image.
> fix: incorrect time formatting

- deployment/united-manufacturing-hub/templates/factoryinput/statefulset.yaml
- deployment/united-manufacturing-hub/values.yaml
- golang/cmd/factoryinput/main.go
This PR adds the possibility to change some env variables of factoryinput from values.yaml. Moreover, adds the missing env variable `MQTT_QUEUE_HANDLER`.
Merged into [fix/1453/factoryinput-not-working-if-mqtt-tls-is-enabled](https://github.com/united-manufacturing-hub/united-manufacturing-hub/tree/fix/1453/factoryinput-not-working-if-mqtt-tls-is-enabled) in order to begin working on issue #1453  
Fixes #1454 
Not tested because related to #1453 
*none*
*none*
> Fix: missing env variables for factoryinput

- deployment/barcodereader/Dockerfile
- deployment/custom-microservice-tester/Dockerfile
- deployment/factoryinput/Dockerfile
- deployment/factoryinsight/Dockerfile
- deployment/grafana-proxy/Dockerfile
- deployment/kafka-bridge/Dockerfile
- deployment/kafka-debug/Dockerfile
- deployment/kafka-init/Dockerfile
- deployment/kafka-state-detector/Dockerfile
- deployment/kafka-to-postgresql/Dockerfile
- deployment/mqtt-bridge/Dockerfile
- deployment/mqtt-kafka-bridge/Dockerfile
- deployment/sensorconnect/Dockerfile
This PR fixes the `go build` command, that doesn't allow `-msan` and `-asan` flags if `-race` is present
> Remove conflicting flags from `go build` command

- deployment/united-manufacturing-hub/templates/hivemq/statefulset.yaml
This PR removes the `-race` tag from the hivemq-init image, since that image does not exists
> Remove `-race` tag from hivemq-init image

- golang/cmd/barcodereader/main.go
- golang/cmd/kafka-init/kafka.go
- golang/cmd/mqtt-kafka-bridge/kafka_processor/kafka.go
Adjust to [Sarama-Kafka-Wrapper](https://github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper) API changes introduced in this [commit](https://github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper/commit/2eb80ec06c75163ec6269e631b89238410be2e58).
Should fix previous docker build errors of `barcodereader`, `kafka-init` and `mqtt-kafka-bridge`.
> refactor ConsumerName fields of kafka client options to ConsumerGroupId

- golang/cmd/data-bridge/main.go
This PR adds the base functionality for the new data bridge.
The `main()` functions checks for the env variables and validates them, starts the health check, and defines the clients.
I decided to use a generic `client` interface in order to have a cleaner code. Both kafka and MQTT will implement those methods, each in their own way
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/344
PS: it'ok that the codecov checks fails, as some of the functions are not yet implemented. Notice that this PR wants to merge into `feat/338/create-data-bridge`, so that we can test in that branch once that all the functionalities have been added
> Add base functionality for data bridge

- golang/cmd/data-bridge/kafka.go
- golang/cmd/data-bridge/main.go
This PR adds the kafka client that implements the `client` interface.
When using the `startConsumer` method, it starts reading the messages from the broker and sending them to the `msgChan`
When using the `startProducer` method, it reads the messages from `msgChan`, transforms them from mqtt-style to kafka-style (if necessary) and does the splitting
I would have added unit tests, but unfortunately, due to the fact that I used the sarama wrapper, I couldn't mock the kafka client in order to test the consumer and producer functionalities,
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/345
> Add kafka handler

- golang/cmd/data-bridge/main.go
- golang/cmd/data-bridge/mqtt.go
- golang/go.mod
- golang/go.sum
This PR adds the MQTT client that implements the `client` interface.
When using the `startConsumer` method, it starts reading the messages from the broker and sending them to the `msgChan`.
When using the `startProducer` method, it reads the messages from `msgChan`, transforms them from kafka-style to mqtt-style (if necessary) and does the splitting
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/346
> Add MQTT handler

- deployment/united-manufacturing-hub/templates/nodered/statefulset.yaml
- deployment/united-manufacturing-hub/values.yaml
This pr removes the last remaining images that where not on management.umh.app and are not hardcoded in external dependencies. (Our containerd overwrite takes care of those)
This is a bug fix for the existing https://github.com/united-manufacturing-hub/MgmtIssues/issues/1050 user journey
> Added overwrites for last images

- deployment/hivemq-init/Dockerfile
- deployment/hivemq-init/runner.sh
- deployment/united-manufacturing-hub/templates/hivemq/statefulset.yaml
- deployment/united-manufacturing-hub/values.yaml
This change upgrades hivemq-ce 2023.7 to 2024.1. Deployment and basic flow (nodered, mqtt, kafka, umh-v2 db) are tested on the local cluster.
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1647#issuecomment-1969430276
- https://github.com/united-manufacturing-hub/MgmtIssues/issues/1647#issuecomment-1969461151
- Increased broker efficiency by reducing end-to-end message latency, CPU usage, and memory footprint.
- Improved error handling in the internal executor service to facilitate debugging
- etc.
closes united-manufacturing-hub/MgmtIssues/issues/1647
> Upgrade hivemq

- .github/workflows/run_go_tests_k2pg-v2.yaml
- deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
- golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-product-type.go
- golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-product.go
- golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-shift.go
- golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-state.go
- golang/cmd/kafka-to-postgresql-v2/postgresql/analytics-work-order.go
- golang/cmd/kafka-to-postgresql-v2/postgresql/analytics_test.go
- golang/cmd/kafka-to-postgresql-v2/postgresql/lru.go
- golang/cmd/kafka-to-postgresql-v2/worker/analytics.go
pg internally converts camelCase to lowercase, therefore this pr changes our names to snake_case (this is also in line with _historian).
Based on #1757
> [#1662 (1)] Fix names in postgresql tables and coloumns

- deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
pg_stat_statements is an observability plugin that provides valuable metrics on TimescaleDB performance. UMH intends to integrate these metrics into the Management Console, enhancing visibility into the database’s activity and health.
> [ENG-1123] Install pg_stat_statements plugin for timescaledb

- deployment/united-manufacturing-hub/templates/modbussimulator/config.yaml
- deployment/united-manufacturing-hub/templates/modbussimulator/deployment.yaml
- deployment/united-manufacturing-hub/templates/modbussimulator/service.yaml
The default port number of the Modbus simulator that we use is( https://github.com/cybcon/modbus-server) is 5020 but the helm template had it as 502. PR changes the port 502 to 5020
> [ENG-1708] Fix typo in Port number for Modbus simulator

- deployment/united-manufacturing-hub/templates/modbussimulator/deployment.yaml
- deployment/united-manufacturing-hub/templates/opcuasimulatorv2/deployment.yaml
- The command for modbus simulator is fixed according to the source repo https://github.com/cybcon/modbus-server/blob/main/Dockerfile#L23
- The opc plc image tag is fixed
> [ENG-1691] Fix modbus simulator command

- umh-core/pkg/fsm/dataflowcomponent/fsm_callbacks.go
- umh-core/pkg/fsm/dataflowcomponent/machine.go
- umh-core/pkg/fsm/dataflowcomponent/models.go
- umh-core/pkg/metrics/metrics.go
The PR configures the state machine transitions for the Dataflowcomponent FSM and adds the necessary call back functions.
> [ENG-2801] Configure Statemachine Transitions for Dataflowcomponent FSM

- umh-core/Dockerfile
- umh-core/Makefile
- umh-core/cmd/main.go
- umh-core/internal/pprof/no_pprof.go
- umh-core/internal/pprof/pprof.go
This pr cleanup the makefile a bit, by combining the build targets.
It now also allows you to do:
`make test-X` (normal build)
`make test-X FLAVOR=pprof` (enables pprof on port 6060)
`make test-X FLAVOR=debug` (enables delve on port 40000)
> Cleanup makefile & add pprof flag

- umh-core/pkg/communicator/actions/actions.go
- umh-core/pkg/communicator/actions/benthos-log-checker.go
- umh-core/pkg/communicator/actions/deploy-dataflowcomponent.go
- umh-core/pkg/communicator/actions/edit-dataflowcomponent.go
- umh-core/pkg/models/action_models.go
This PR introduces early aborts on benthos config errors and provides the frontend with better error info (i.e. error code) so that it can determine weather to offer the user the retry-option or not. Therefore, we include the SendActionReplyV2 which already existed in UMH Classic. In the frontend, the fetcher checks the action reply error code for the prefix `ERR_RETRY_`  . If it finds the prefix in the error code or no error code at all, the retry option is displayed.
> [ENG-3007] [ENG-3014] Better Errors for DFC deploy and edit

- .github/workflows/build-umh-core.yml
Fixed the "unbound variable" error that happened during release by changing how we handle the webhook secret in bash scripts.
- Problem: The secret likely contains special bash characters like `$something` that bash tries to interpret as variables.
- Fix: Store the secret in a variable at the script level before using it in curl commands, preventing bash from trying to expand stuff inside the secret value.
While this should fix the issue, GitHub Actions environments can be unpredictable sometimes...
> ENG-3037 Fix unbound variable error in notify mc job

- umh-core/docs/README.md
- umh-core/docs/SUMMARY.md
- umh-core/docs/production/metrics.md
- umh-core/docs/reference/configuration-reference.md
- umh-core/docs/umh-core-vs-classic-faq.md
- umh-core/docs/usage/data-flows/bridges.md
- umh-core/docs/usage/data-flows/stream-processor-upcoming.md
- Add 🚧 roadmap markers for upcoming features (bridges, stream processors, enhanced metrics, MQTT plugin, HTTP endpoints)
- Expand bridges.md and stream-processor.md with feature descriptions and link to config reference
- Update metrics.md to distinguish current vs planned Prometheus metrics
- Mark FAQ items for UMH MQTT plugin and HTTP API endpoints as roadmap
- Update README and SUMMARY.md to show feature availability status
- Streamline bridges documentation to reference configuration guide instead of duplicating syntax
Provides clear visibility into what's available now vs coming soon vs future roadmap.
> docs: mark roadmap items consistently throughout documentation

- umh-core/Makefile
- umh-core/cmd/main.go
- umh-core/pkg/communicator/communication_state/communication_state.go
This implements a small routine which will attempt to update the auth token every 1 hours.
Our JWT currently has an expiry of 24 hours, giving it ~24 attempts to refresh before expiry (and even if expired it will continue to re-try).
Imo this is a good balance between reliabilty and keeping the API traffic low.
It also matches our old implementation
See also the companion implementation in https://github.com/united-manufacturing-hub/ManagementConsole/blob/staging/companion/cmd/appstate/appstate.go#L395
I did not implement the part where it decodes the expiry time, as for now i would try to keep this simple.
If on a later date we want to make the refresh interval dynamic based on token expiry time, it should be easily implementable.
It also uses the Watchdog to prevent any "hangs".
> ENG-3050 implement re-authentification routine

- umh-core/pkg/config/streamprocessorserviceconfig/config_customized.go
- umh-core/pkg/service/streamprocessor/runtime_config/runtime_config.go
the `consumer_group` was causing the issue to only allow 1 streamprocessor consuming data, now added creating a hex-string out of the streamprocessorname to apply multiple consumer_groups
> Fix(cfg): allow multiple streamprocessors through consumer_group

- umh-core/.gitignore
- umh-core/Makefile
- umh-core/pkg/fsm/agent_monitor/reconcile.go
- umh-core/pkg/fsm/benthos/reconcile.go
- umh-core/pkg/fsm/benthos_monitor/reconcile.go
- umh-core/pkg/fsm/connection/reconcile.go
- umh-core/pkg/fsm/container/reconcile.go
- umh-core/pkg/fsm/dataflowcomponent/reconcile.go
- umh-core/pkg/fsm/nmap/reconcile.go
- umh-core/pkg/fsm/protocolconverter/reconcile.go
- umh-core/pkg/fsm/redpanda/reconcile.go
- umh-core/pkg/fsm/redpanda_monitor/reconcile.go
- umh-core/pkg/fsm/streamprocessor/reconcile.go
- umh-core/pkg/fsm/topicbrowser/reconcile.go
- umh-core/test/fsm/benthos/benthos_test.go
- umh-core/test/fsm/nmap/nmap_test.go
- umh-core/test/fsm/protocolconverter/protocolconverter_test.go
- umh-core/test/fsm/streamprocessor/manager_test.go
- umh-core/tools/loganalyzer/Makefile
- umh-core/tools/loganalyzer/README.md
- umh-core/tools/loganalyzer/display.go
- umh-core/tools/loganalyzer/errors.go
- umh-core/tools/loganalyzer/main.go
- umh-core/tools/loganalyzer/orphans.go
- umh-core/tools/loganalyzer/parser.go
- umh-core/tools/loganalyzer/recovery.go
- umh-core/tools/loganalyzer/summary_analysis.go
- umh-core/tools/loganalyzer/types.go
- umh-core/tools/loganalyzer/visualize.go
Fixes ENG-3298
Introduces in the first commit ac8cab86365e275fea35feeadda6fc8532a3ec15 a log analyzer package. This is just a intermediary program that I thought we can extend over time to help us in analyzing the logs.
The second commit contains the actual fix here, that was recovered partly from the three large PRs: 8d631c1a0061d0a14ba3f83d3a0cbc4ce023bbc2
More information about what is happening exactly can be found in the ticket description: ENG-3298
After a restart, they will not be stuck anymore in "to_be_created" but might still be in a grey starting state as e.g., Redpanda is degraded (e.g., [ENG-3302](https://linear.app/united-manufacturing-hub/issue/ENG-3302/redpanda-degraded-after-restart-due-to-address-in-use-error))
> ENG-3298 Fix to_be_created issue after agent restarts

- umh-core/internal/fsm/baseFSM.go
- umh-core/internal/fsmtest/s6.go
- umh-core/pkg/fsm/benthos/actions.go
- umh-core/pkg/fsm/benthos/reconcile.go
- umh-core/pkg/fsm/s6/actions.go
- umh-core/pkg/fsm/s6/manager_mock.go
- umh-core/pkg/fsm/s6/models.go
- umh-core/pkg/fsm/s6/reconcile.go
- umh-core/pkg/service/benthos/errors.go
- umh-core/pkg/service/s6/lifecycle.go
- umh-core/pkg/service/s6/lifecycle_test.go
- umh-core/pkg/service/s6/mock.go
- umh-core/pkg/service/s6/s6.go
- umh-core/test/fsm/benthos/manager_test.go
- umh-core/test/fsm/redpanda/state_transition_monitor_test.go
This PR implements directory health detection for S6 services to automatically recover when service directories are missing or corrupted. This fixes the critical issue where FSMs get stuck in infinite loops showing "stopping: not existing" when S6 service directories are deleted or force-removed.
**Fixes:**
- [[ENG-3468](https://linear.app/united-manufacturing-hub/issue/ENG-3468)](https://linear.app/united-manufacturing-hub/issue/ENG-3468): Parent FSM stuck when S6 service returns empty string "not existing"
- [[ENG-3469](https://linear.app/united-manufacturing-hub/issue/ENG-3469)](https://linear.app/united-manufacturing-hub/issue/ENG-3469): Add S6 directory diagnostic logging for troubleshooting
Users are experiencing services stuck in states like:
- `"stopping: S6 is not stopped, …
> fix: implement DirectoryHealth detection for S6 service self-healing
